# Generated by Django 4.1 on 2023-02-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True, verbose_name='Message id')),
                ('user', models.CharField(max_length=255, verbose_name='User id')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuoteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255, verbose_name='Quote')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='admins.searchquotegroup')),
            ],
        ),
    ]
